// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./components/organisms/Comment.vue')['default']
    CommentButtons: typeof import('./components/atoms/CommentButtons.vue')['default']
    Minus: typeof import('./components/icons/Minus.vue')['default']
    Plus: typeof import('./components/atoms/Plus.vue')['default']
    PlusMinusButton: typeof import('./components/molecules/PlusMinusButton.vue')['default']
  }
}

export { }
